version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - misspell
  settings:
    errcheck:
      check-type-assertions: true
  exclusions:
    paths:
      - testdata

formatters:
  enable:
    - gofmt
    - goimports
