# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
  - main: ./cmd/gaze
    binary: gaze
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Tag}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.CommitDate}}

archives:
  - formats:
      - tar.gz
    name_template: >-
      gaze_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Documentation
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999
  filters:
    exclude:
      - '^chore:'

homebrew_casks:
  - name: gaze
    directory: Casks
    repository:
      owner: unbound-force
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/unbound-force/gaze
    description: >-
      Test quality analysis via side effect detection for Go
    binaries:
      - gaze
    skip_upload: auto
    commit_msg_template: >-
      Brew cask update for {{ .ProjectName }} version {{ .Tag }}
